# Generated by Django 5.0.2 on 2024-03-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
